[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tiny_http = "0.12.0"
urlencoding = "2.1.3"
ws = "0.9.2"
